### ISSUE TITLE
linux-steam-integration compat-libgrypt issues

### ISSUE THREAD

**Issue by ciddan** [alunux/rpm-specfiles#1]
Hey,

Trying to install LSI from your Copr repo and it won't install due to:
Error: 
 Problem: conflicting requests
  - nothing provides compat-libgcrypt(x86-32) needed by linux-steam-integration-0.3-5.fc26.x86_64

Your repo seems to provide an x86_64 version of the package. Is the dependency misconfigured?

**Comment by alunux** [comment]
@ciddan Thank you for open this issue. Sorry about that. I forgot to write the installation instructions. Because Copr is still not enabling multilib repo by default, we need to modify the repo file at `/etc/yum.repos.d/`. So, LSI repo (`/etc/yum.repos.d/_copr_alunux-linux-steam-integration.repo`) looks like this:

```
[alunux-linux-steam-integration-x86_64]
name=Copr repo for linux-steam-integration owned by alunux - x86_64
baseurl=https://copr-be.cloud.fedoraproject.org/results/alunux/linux-steam-integration/fedora-$releasever-x86_64/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/alunux/linux-steam-integration/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1

[alunux-linux-steam-integration-i386]
name=Copr repo for linux-steam-integration owned by alunux - i686
baseurl=https://copr-be.cloud.fedoraproject.org/results/alunux/linux-steam-integration/fedora-$releasever-i386/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/alunux/linux-steam-integration/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

**Comment by ciddan** [comment]
Thanks, installation works now!
Now I just gotta figure out why steam instantly crashes when I run it. Ah well, one step closer I suppose :)

**Comment by alunux** [comment]
@ciddan i had updated the Copr page :)
https://copr.fedorainfracloud.org/coprs/alunux/linux-steam-integration/

**Comment by ciddan** [comment]
FYI, this might be worth including in your help text:
https://github.com/ValveSoftware/steam-for-linux/issues/3248#issuecomment-201888194
Apparently lots of users (me included) are having issues getting steam to run if they install the Nvidia drivers before installing Steam.
In order to fix the issue I had I just had to re-install the Nvidia driver and then Steam started up.
