### ISSUE TITLE
Fedora 31 Budgie Desktop build failed.

### ISSUE THREAD

**Issue by LyesSaadi** [alunux/rpm-specfiles#11]
Everything is in the title.
Unfortunately, build info were deleted, I'll try to run a build to see why it fails.

**Comment by alunux** [comment]
It's caused by this part:
```
%if 0%{?fedora} >= 31
BuildRequires: pkgconfig(libmutter-5) >= 3.34.0
%endif
```
You should wait until GNOME 3.34.x is available in Fedora 31 repository.

**Comment by LyesSaadi** [comment]
Ohh, so that's why :smile:!
Sorry for the inconvenience ;)!
But, Mutter/Gnome 3.34.x is [available on official repos since the 9th](https://koji.fedoraproject.org/koji/buildinfo?buildID=1374828), in fact, you [builded Budgie for Fedora](https://copr.fedorainfracloud.org/coprs/alunux/budgie-desktop-git/build/1030672/) 7 hours before 3.34 is available XD (on testing at least). What a coincidence :stuck_out_tongue:!

**Comment by alunux** [comment]
Aha, let me rebuild it. Thank you for your report!

**Comment by LyesSaadi** [comment]
It succeeded! Yay :tada:!

**Comment by LyesSaadi** [comment]
Well, budgie crash on Fedora 31 (Silverblue) when opening a session... But that is not related to this repo (unless it's one of the patches), it's a budgie issue.
