### ISSUE TITLE
Installing budgie-vala-panel-appmenu-plugin fails

### ISSUE THREAD

**Issue by sirredbeard** [alunux/rpm-specfiles#4]
First of all, thank you for providing this.

Second, I am encountering the following when installing on an updated Fedora 28 install:

```
sudo dnf install budgie-desktop budgie-brightness-control-applet budgie-haste-applet budgie-pixel-saver-applet budgie-screenshot-applet budgie-vala-panel-appmenu-plugin
Last metadata expiration check: 0:00:59 ago on Tue 15 May 2018 07:33:03 PM EDT.
Error: 
Problem: package budgie-vala-panel-appmenu-plugin-0.6.1-3.fc28.x86_64 requires appmenu-qt5, but none of the providers can be installed
   - conflicting requests
   - nothing provides libQt5Gui.so.5(Qt_5_PRIVATE_API) needed by appmenu-qt5-0.3.0+16.10.20160628.1-2.fc26.i686
   - nothing provides libQt5Gui.so.5(Qt_5_PRIVATE_API)(64bit) needed by appmenu-qt5-0.3.0+16.10.20160628.1-2.fc26.x86_64
```

**Comment by sirredbeard** [comment]
The work around is:

`sudo dnf install qt5-qtbase-devel first`

Can it be tagged as a dependency for budgie-vala-panel-appmenu-plugin?

**Comment by alunux** [comment]
The broken package here is appmenu-qt5. qt5-qtbase-devel is a development package for qt5-qt-base, not used on runtime. The maintainer of appmenu-qt5 needs to rebuild their package against latest Qt5 to fix this issue.

**Comment by alunux** [comment]
Fedora Rawhide already has [the latest build of appmenu-qt5](https://koji.fedoraproject.org/koji/buildinfo?buildID=1063794), we still need to wait until the latest package land on F27 and F28 stable repo.

**Comment by sirredbeard** [comment]
Thank you for looking into this. I appreciate you bringing Budgie, particularly the git-based version, to Fedora.

**Comment by alunux** [comment]
Fedora Copr gives me more control than Fedora main repositories. I hope you enjoy with the repo. Thank you for reporting this issue :)

**Comment by alunux** [comment]
Can you try again? I pushed appmenu-qt5 to copr because there is no update from main repo.
